/*
Route Optimization OptiFlow

With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.

API version: 1.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the VehicleStart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VehicleStart{}

// VehicleStart Describes the start of a route assigned to the vehicle.
type VehicleStart struct {
	// The unique identifier of the location where a route assigned to the vehicle must start. When omitted, the route starts at the location of the first stop.
	LocationId *string `json:"locationId,omitempty" validate:"regexp=^[a-zA-Z0-9_-]{1,36}$"`
	// The earliest point in time a route assigned to the vehicle may start. This must be not be later than the vehicle's latest end time. When used in conjunction with a latest start time, the earliest start time must not be later than the latest start time. Formatted according to [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). The date must not be before `1970-01-01T00:00:00+00:00` nor after `2037-12-31T23:59:59+00:00`. The date must provide an offset to UTC.
	EarliestStartTime time.Time `json:"earliestStartTime"`
	// The latest point in time a route assigned to the vehicle may start. This must not be earlier than the vehicle's earliest start time nor later than the vehicle's earliest end time. Formatted according to [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). The date must not be before `1970-01-01T00:00:00+00:00` nor after `2037-12-31T23:59:59+00:00`. The date must provide an offset to UTC.
	LatestStartTime *time.Time `json:"latestStartTime,omitempty"`
	// Describes how long [s] it takes for the vehicle to depart at its start location after the route starts.
	Duration *int32 `json:"duration,omitempty"`
}

type _VehicleStart VehicleStart

// NewVehicleStart instantiates a new VehicleStart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicleStart(earliestStartTime time.Time) *VehicleStart {
	this := VehicleStart{}
	this.EarliestStartTime = earliestStartTime
	var duration int32 = 0
	this.Duration = &duration
	return &this
}

// NewVehicleStartWithDefaults instantiates a new VehicleStart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleStartWithDefaults() *VehicleStart {
	this := VehicleStart{}
	var duration int32 = 0
	this.Duration = &duration
	return &this
}

// GetLocationId returns the LocationId field value if set, zero value otherwise.
func (o *VehicleStart) GetLocationId() string {
	if o == nil || IsNil(o.LocationId) {
		var ret string
		return ret
	}
	return *o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleStart) GetLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.LocationId) {
		return nil, false
	}
	return o.LocationId, true
}

// HasLocationId returns a boolean if a field has been set.
func (o *VehicleStart) HasLocationId() bool {
	if o != nil && !IsNil(o.LocationId) {
		return true
	}

	return false
}

// SetLocationId gets a reference to the given string and assigns it to the LocationId field.
func (o *VehicleStart) SetLocationId(v string) {
	o.LocationId = &v
}

// GetEarliestStartTime returns the EarliestStartTime field value
func (o *VehicleStart) GetEarliestStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EarliestStartTime
}

// GetEarliestStartTimeOk returns a tuple with the EarliestStartTime field value
// and a boolean to check if the value has been set.
func (o *VehicleStart) GetEarliestStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EarliestStartTime, true
}

// SetEarliestStartTime sets field value
func (o *VehicleStart) SetEarliestStartTime(v time.Time) {
	o.EarliestStartTime = v
}

// GetLatestStartTime returns the LatestStartTime field value if set, zero value otherwise.
func (o *VehicleStart) GetLatestStartTime() time.Time {
	if o == nil || IsNil(o.LatestStartTime) {
		var ret time.Time
		return ret
	}
	return *o.LatestStartTime
}

// GetLatestStartTimeOk returns a tuple with the LatestStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleStart) GetLatestStartTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LatestStartTime) {
		return nil, false
	}
	return o.LatestStartTime, true
}

// HasLatestStartTime returns a boolean if a field has been set.
func (o *VehicleStart) HasLatestStartTime() bool {
	if o != nil && !IsNil(o.LatestStartTime) {
		return true
	}

	return false
}

// SetLatestStartTime gets a reference to the given time.Time and assigns it to the LatestStartTime field.
func (o *VehicleStart) SetLatestStartTime(v time.Time) {
	o.LatestStartTime = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *VehicleStart) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleStart) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *VehicleStart) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *VehicleStart) SetDuration(v int32) {
	o.Duration = &v
}

func (o VehicleStart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VehicleStart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LocationId) {
		toSerialize["locationId"] = o.LocationId
	}
	toSerialize["earliestStartTime"] = o.EarliestStartTime
	if !IsNil(o.LatestStartTime) {
		toSerialize["latestStartTime"] = o.LatestStartTime
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	return toSerialize, nil
}

func (o *VehicleStart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"earliestStartTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVehicleStart := _VehicleStart{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVehicleStart)

	if err != nil {
		return err
	}

	*o = VehicleStart(varVehicleStart)

	return err
}

type NullableVehicleStart struct {
	value *VehicleStart
	isSet bool
}

func (v NullableVehicleStart) Get() *VehicleStart {
	return v.value
}

func (v *NullableVehicleStart) Set(val *VehicleStart) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleStart) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleStart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleStart(val *VehicleStart) *NullableVehicleStart {
	return &NullableVehicleStart{value: val, isSet: true}
}

func (v NullableVehicleStart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleStart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


