/*
Route Optimization OptiFlow

With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.

API version: 1.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderLoadingIncompatibilityConstraint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderLoadingIncompatibilityConstraint{}

// OrderLoadingIncompatibilityConstraint Describes a constraint where orders are forbidden to be loaded or unloaded while other orders are loaded in the vehicle.
type OrderLoadingIncompatibilityConstraint struct {
	// Orders belonging to this category must be loaded in the vehicle for this constraint to apply. The constraint will be ignored when no order belongs to this category.
	LoadedOrderCategory string `json:"loadedOrderCategory" validate:"regexp=^[a-zA-Z0-9_-]{1,36}$"`
	// Orders belonging to this category cannot be loaded or unloaded while the constraint applies. The constraint will be ignored when no order belongs to this category.
	ForbiddenOrderCategory string `json:"forbiddenOrderCategory" validate:"regexp=^[a-zA-Z0-9_-]{1,36}$"`
	// The category of vehicles to which this constraint applies. When omitted the constraint applies to all vehicles. The constraint will be ignored when no vehicle belongs to this category.
	VehicleCategory *string `json:"vehicleCategory,omitempty" validate:"regexp=^[a-zA-Z0-9_-]{1,36}$"`
}

type _OrderLoadingIncompatibilityConstraint OrderLoadingIncompatibilityConstraint

// NewOrderLoadingIncompatibilityConstraint instantiates a new OrderLoadingIncompatibilityConstraint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderLoadingIncompatibilityConstraint(loadedOrderCategory string, forbiddenOrderCategory string) *OrderLoadingIncompatibilityConstraint {
	this := OrderLoadingIncompatibilityConstraint{}
	this.LoadedOrderCategory = loadedOrderCategory
	this.ForbiddenOrderCategory = forbiddenOrderCategory
	return &this
}

// NewOrderLoadingIncompatibilityConstraintWithDefaults instantiates a new OrderLoadingIncompatibilityConstraint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderLoadingIncompatibilityConstraintWithDefaults() *OrderLoadingIncompatibilityConstraint {
	this := OrderLoadingIncompatibilityConstraint{}
	return &this
}

// GetLoadedOrderCategory returns the LoadedOrderCategory field value
func (o *OrderLoadingIncompatibilityConstraint) GetLoadedOrderCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LoadedOrderCategory
}

// GetLoadedOrderCategoryOk returns a tuple with the LoadedOrderCategory field value
// and a boolean to check if the value has been set.
func (o *OrderLoadingIncompatibilityConstraint) GetLoadedOrderCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoadedOrderCategory, true
}

// SetLoadedOrderCategory sets field value
func (o *OrderLoadingIncompatibilityConstraint) SetLoadedOrderCategory(v string) {
	o.LoadedOrderCategory = v
}

// GetForbiddenOrderCategory returns the ForbiddenOrderCategory field value
func (o *OrderLoadingIncompatibilityConstraint) GetForbiddenOrderCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ForbiddenOrderCategory
}

// GetForbiddenOrderCategoryOk returns a tuple with the ForbiddenOrderCategory field value
// and a boolean to check if the value has been set.
func (o *OrderLoadingIncompatibilityConstraint) GetForbiddenOrderCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForbiddenOrderCategory, true
}

// SetForbiddenOrderCategory sets field value
func (o *OrderLoadingIncompatibilityConstraint) SetForbiddenOrderCategory(v string) {
	o.ForbiddenOrderCategory = v
}

// GetVehicleCategory returns the VehicleCategory field value if set, zero value otherwise.
func (o *OrderLoadingIncompatibilityConstraint) GetVehicleCategory() string {
	if o == nil || IsNil(o.VehicleCategory) {
		var ret string
		return ret
	}
	return *o.VehicleCategory
}

// GetVehicleCategoryOk returns a tuple with the VehicleCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderLoadingIncompatibilityConstraint) GetVehicleCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.VehicleCategory) {
		return nil, false
	}
	return o.VehicleCategory, true
}

// HasVehicleCategory returns a boolean if a field has been set.
func (o *OrderLoadingIncompatibilityConstraint) HasVehicleCategory() bool {
	if o != nil && !IsNil(o.VehicleCategory) {
		return true
	}

	return false
}

// SetVehicleCategory gets a reference to the given string and assigns it to the VehicleCategory field.
func (o *OrderLoadingIncompatibilityConstraint) SetVehicleCategory(v string) {
	o.VehicleCategory = &v
}

func (o OrderLoadingIncompatibilityConstraint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderLoadingIncompatibilityConstraint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["loadedOrderCategory"] = o.LoadedOrderCategory
	toSerialize["forbiddenOrderCategory"] = o.ForbiddenOrderCategory
	if !IsNil(o.VehicleCategory) {
		toSerialize["vehicleCategory"] = o.VehicleCategory
	}
	return toSerialize, nil
}

func (o *OrderLoadingIncompatibilityConstraint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"loadedOrderCategory",
		"forbiddenOrderCategory",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderLoadingIncompatibilityConstraint := _OrderLoadingIncompatibilityConstraint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderLoadingIncompatibilityConstraint)

	if err != nil {
		return err
	}

	*o = OrderLoadingIncompatibilityConstraint(varOrderLoadingIncompatibilityConstraint)

	return err
}

type NullableOrderLoadingIncompatibilityConstraint struct {
	value *OrderLoadingIncompatibilityConstraint
	isSet bool
}

func (v NullableOrderLoadingIncompatibilityConstraint) Get() *OrderLoadingIncompatibilityConstraint {
	return v.value
}

func (v *NullableOrderLoadingIncompatibilityConstraint) Set(val *OrderLoadingIncompatibilityConstraint) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderLoadingIncompatibilityConstraint) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderLoadingIncompatibilityConstraint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderLoadingIncompatibilityConstraint(val *OrderLoadingIncompatibilityConstraint) *NullableOrderLoadingIncompatibilityConstraint {
	return &NullableOrderLoadingIncompatibilityConstraint{value: val, isSet: true}
}

func (v NullableOrderLoadingIncompatibilityConstraint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderLoadingIncompatibilityConstraint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


