/*
Route Optimization

With the Route Optimization service you can schedule and optimize the routes of your fleet.

API version: 1.11
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package optiflow

import (
	"encoding/json"
)

// checks if the DepotLocationAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DepotLocationAttributes{}

// DepotLocationAttributes Attributes for a location of type DEPOT.
type DepotLocationAttributes struct {
	// The service time [s] that is required each time this location is visited in order to pick up goods. The location-dependent service time represents, for example, the time to enter the premises or to register at a depot. Besides a location-dependent service time, the user may specify additional vehicle-dependent and transport-dependent service times at the vehicles and the transports respectively.
	ServiceTimePerPickupStop *int32 `json:"serviceTimePerPickupStop,omitempty"`
	// The service time [s] that is required each time this location is visited in order to deliver goods. The location-dependent service time represents, for example, the time to enter the premises or to register at a depot. Besides a location-dependent service time, the user may specify additional vehicle-dependent and transport-dependent service times at the vehicles and the transports respectively.
	ServiceTimePerDeliveryStop *int32 `json:"serviceTimePerDeliveryStop,omitempty"`
}

// NewDepotLocationAttributes instantiates a new DepotLocationAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDepotLocationAttributes() *DepotLocationAttributes {
	this := DepotLocationAttributes{}
	var serviceTimePerPickupStop int32 = 0
	this.ServiceTimePerPickupStop = &serviceTimePerPickupStop
	var serviceTimePerDeliveryStop int32 = 0
	this.ServiceTimePerDeliveryStop = &serviceTimePerDeliveryStop
	return &this
}

// NewDepotLocationAttributesWithDefaults instantiates a new DepotLocationAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDepotLocationAttributesWithDefaults() *DepotLocationAttributes {
	this := DepotLocationAttributes{}
	var serviceTimePerPickupStop int32 = 0
	this.ServiceTimePerPickupStop = &serviceTimePerPickupStop
	var serviceTimePerDeliveryStop int32 = 0
	this.ServiceTimePerDeliveryStop = &serviceTimePerDeliveryStop
	return &this
}

// GetServiceTimePerPickupStop returns the ServiceTimePerPickupStop field value if set, zero value otherwise.
func (o *DepotLocationAttributes) GetServiceTimePerPickupStop() int32 {
	if o == nil || IsNil(o.ServiceTimePerPickupStop) {
		var ret int32
		return ret
	}
	return *o.ServiceTimePerPickupStop
}

// GetServiceTimePerPickupStopOk returns a tuple with the ServiceTimePerPickupStop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepotLocationAttributes) GetServiceTimePerPickupStopOk() (*int32, bool) {
	if o == nil || IsNil(o.ServiceTimePerPickupStop) {
		return nil, false
	}
	return o.ServiceTimePerPickupStop, true
}

// HasServiceTimePerPickupStop returns a boolean if a field has been set.
func (o *DepotLocationAttributes) HasServiceTimePerPickupStop() bool {
	if o != nil && !IsNil(o.ServiceTimePerPickupStop) {
		return true
	}

	return false
}

// SetServiceTimePerPickupStop gets a reference to the given int32 and assigns it to the ServiceTimePerPickupStop field.
func (o *DepotLocationAttributes) SetServiceTimePerPickupStop(v int32) {
	o.ServiceTimePerPickupStop = &v
}

// GetServiceTimePerDeliveryStop returns the ServiceTimePerDeliveryStop field value if set, zero value otherwise.
func (o *DepotLocationAttributes) GetServiceTimePerDeliveryStop() int32 {
	if o == nil || IsNil(o.ServiceTimePerDeliveryStop) {
		var ret int32
		return ret
	}
	return *o.ServiceTimePerDeliveryStop
}

// GetServiceTimePerDeliveryStopOk returns a tuple with the ServiceTimePerDeliveryStop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DepotLocationAttributes) GetServiceTimePerDeliveryStopOk() (*int32, bool) {
	if o == nil || IsNil(o.ServiceTimePerDeliveryStop) {
		return nil, false
	}
	return o.ServiceTimePerDeliveryStop, true
}

// HasServiceTimePerDeliveryStop returns a boolean if a field has been set.
func (o *DepotLocationAttributes) HasServiceTimePerDeliveryStop() bool {
	if o != nil && !IsNil(o.ServiceTimePerDeliveryStop) {
		return true
	}

	return false
}

// SetServiceTimePerDeliveryStop gets a reference to the given int32 and assigns it to the ServiceTimePerDeliveryStop field.
func (o *DepotLocationAttributes) SetServiceTimePerDeliveryStop(v int32) {
	o.ServiceTimePerDeliveryStop = &v
}

func (o DepotLocationAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DepotLocationAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceTimePerPickupStop) {
		toSerialize["serviceTimePerPickupStop"] = o.ServiceTimePerPickupStop
	}
	if !IsNil(o.ServiceTimePerDeliveryStop) {
		toSerialize["serviceTimePerDeliveryStop"] = o.ServiceTimePerDeliveryStop
	}
	return toSerialize, nil
}

type NullableDepotLocationAttributes struct {
	value *DepotLocationAttributes
	isSet bool
}

func (v NullableDepotLocationAttributes) Get() *DepotLocationAttributes {
	return v.value
}

func (v *NullableDepotLocationAttributes) Set(val *DepotLocationAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDepotLocationAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDepotLocationAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDepotLocationAttributes(val *DepotLocationAttributes) *NullableDepotLocationAttributes {
	return &NullableDepotLocationAttributes{value: val, isSet: true}
}

func (v NullableDepotLocationAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDepotLocationAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


