name: Update Go Client from OpenAPI Spec

on:
  schedule:
    - cron: '0 * * * *' # runs hourly
  workflow_dispatch:     # allows manual run

jobs:
  regenerate-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Fetch all branches
        run: git fetch -a

      - name: Checkout to new-version
        run: git switch new-version 

      - name: Install OpenAPI Generator CLI via NPM
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Remove previously generated client
        run: rm -rf * 

      - name: Generate Go client from OpenAPI spec
        run: |
          openapi-generator-cli generate \
            -g go \
            -i https://api.myptv.com/meta/services/routeoptimization/optiflow/v1/openapi.json \
            -o .

      - name: Cherry-pick required commits
        run: |
          git cherry-pick f6e633dadca0d15bb402e384ed6c6feb10ebe6c6|| echo "Cherry-pick failed or already applied"
          git cherry-pick e60f99ed41bff620b9babfaef3a93c6362cd0ec4|| echo "Cherry-pick failed or already applied"

      - name: Commit regenerated client
        run: |
          git config user.name "dropon-bot"
          git config user.email "bot@dropon.io"
          git add .
          git commit -m "Regenerate Go client from OpenAPI spec" || echo "No changes to commit"

      - name: Check if something changed with git diff
        id: changes
        run: |
          DIFF_COUNT=$(git diff new-version..main | wc -l | xargs)
          echo "Count of different lines: $DIFF_COUNT"
          echo "diff_count=$DIFF_COUNT" >> $GITHUB_OUTPUT

      - name: Force push to new-version 
        if: steps.changes.outputs.diff_count != '0'
        run: git push origin new-version --force
